# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0002_auto_20161101_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
