# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0003_contract_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='additional_contacts',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
