# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0004_auto_20161102_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('rent_preferential', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_garage_included', models.BooleanField()),
                ('rent_for_garage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='lease_end',
            new_name='signed_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_garage_included',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lease_start',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='rent_for_garage',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='rent_preferential',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='security_deposit_current_balance',
        ),
        migrations.AlterField(
            model_name='contract',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcrm.Apartment'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcrm.ContractConditions'),
        ),
        migrations.AddField(
            model_name='contractconditions',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentcrm.Contract'),
        ),
    ]
