# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0005_auto_20161104_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='contract',
            new_name='contractconditions',
        ),
    ]
