# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0006_auto_20161104_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractconditions',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractconditions',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcrm.Contract'),
        ),
    ]
