# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0007_auto_20161105_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRenewalOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_term', models.IntegerField(default=1)),
                ('rent_legal_one_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_preferential_one_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_legal_two_years', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_preferential_two_years', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_garage_included', models.BooleanField()),
                ('rent_for_garage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_sent', models.BooleanField()),
                ('is_accepted', models.BooleanField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcrm.Contract')),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
