# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:10
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0008_auto_20161106_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractconditions',
            name='rent_for_garage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='contractconditions',
            name='rent_preferential',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='contractconditions',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
