# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0010_apartment_occupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='occupied',
        ),
    ]
