# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0011_remove_apartment_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='new_term',
            field=models.IntegerField(choices=[(1, 'One year term'), (2, 'Two year term')]),
        ),
    ]
