# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0012_auto_20161107_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaserenewaloffer',
            name='contract',
        ),
        migrations.AddField(
            model_name='leaserenewaloffer',
            name='contract_conditions',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='rentcrm.ContractConditions'),
            preserve_default=False,
        ),
    ]
