# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0013_auto_20161107_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserenewaloffer',
            name='date_issued',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='contract_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcrm.Contract'),
        ),
    ]
