# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0014_auto_20161107_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaserenewaloffer',
            old_name='contract_conditions',
            new_name='contract',
        ),
    ]
