# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 10:51
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0016_auto_20161107_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractconditions',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='contractconditions',
        ),
        migrations.AddField(
            model_name='contract',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentcrm.Contract'),
            preserve_default=False,
        ),
    ]
