# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0018_auto_20161112_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apt_num',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='lease_term',
            field=models.IntegerField(choices=[(1, 'One year'), (2, 'Two years')], default=1),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='additional_contacts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
