# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0019_auto_20161112_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apt_num',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contractconditions',
            name='rent_preferential',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set([('apt_num', 'building')]),
        ),
    ]
