# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0020_auto_20161113_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractconditions',
            options={'verbose_name_plural': 'Contract conditions'},
        ),
        migrations.AlterField(
            model_name='building',
            name='has_garage',
            field=models.BooleanField(verbose_name='Garage'),
        ),
    ]
