# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0021_auto_20161116_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_sum', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='contractconditions',
            name='is_garage_included',
            field=models.BooleanField(verbose_name='Garage'),
        ),
        migrations.AddField(
            model_name='discount',
            name='contract_conditions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentcrm.ContractConditions'),
        ),
    ]
