# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0023_auto_20161117_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='contract_conditions',
        ),
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='is_garage_included',
            field=models.BooleanField(verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='rent_for_garage',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
