# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0024_auto_20161117_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserenewaloffer',
            name='is_response_received',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='new_term',
            field=models.IntegerField(choices=[(1, 'One year term'), (2, 'Two years term')]),
        ),
    ]
