# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0026_auto_20161119_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='is_accepted',
            field=models.BooleanField(choices=[(True, 'Offer accepted'), (False, 'Offer rejected')], verbose_name='Accepted'),
        ),
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='is_response_received',
            field=models.BooleanField(default=False),
        ),
    ]
