# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0027_auto_20161119_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractConditions',
            new_name='ContractCondition',
        ),
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='is_accepted',
            field=models.BooleanField(choices=[(True, 'Offer accepted'), (False, 'Offer rejected')], verbose_name='Offer status'),
        ),
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='is_response_received',
            field=models.BooleanField(default=False, verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='is_sent',
            field=models.BooleanField(verbose_name='Sent'),
        ),
    ]
