# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0028_auto_20161124_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaserenewaloffer',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='leaserenewaloffer',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='leaserenewaloffer',
            name='new_term',
        ),
        migrations.AddField(
            model_name='leaserenewaloffer',
            name='lease_period',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentcrm.ContractCondition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaserenewaloffer',
            name='tenant_choice',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'One year term'), (2, 'Two years term'), (0, 'No renew')], null=True),
        ),
    ]
