# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0031_auto_20161126_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcondition',
            name='lease_end',
            field=models.DateField(verbose_name='Period end'),
        ),
        migrations.AlterField(
            model_name='contractcondition',
            name='lease_start',
            field=models.DateField(verbose_name='Period start'),
        ),
    ]
