# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0032_auto_20161126_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='lease_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='lease_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
