# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0034_auto_20161209_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='main_tenant_name',
        ),
    ]
