# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0035_remove_contract_main_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='main_tenant_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
