# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0037_auto_20161211_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcrm.Contract')),
            ],
        ),
    ]
