# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0038_rentadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apt_num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contract',
            name='lease_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaserenewaloffer',
            name='date_issued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
