# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0039_auto_20161228_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['apt_num']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='rentadjustment',
            options={'ordering': ['-date']},
        ),
    ]
