# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcrm', '0040_auto_20170112_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['building__address', 'apt_num']},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['address']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='rentadjustment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='apartment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='lease_term',
            field=models.IntegerField(choices=[(1, 'One year'), (2, 'Two years')], default=1, verbose_name='Initial lease term'),
        ),
        migrations.AlterField(
            model_name='rentadjustment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="Enter negative amount to decrease tenant's debt or positive to increase", max_digits=10),
        ),
    ]
