# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullion', '0002_auto_20161128_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
    ]
